# Use official PHP 8.1 image with Apache
FROM php:8.2-apache

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libicu-dev \
    libzip-dev \
    unzip \
    git \
    zip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev \
    && docker-php-ext-install intl pdo_mysql pdo_pgsql zip gd mbstring xml bcmath

# Enable Apache Rewrite Module
RUN a2enmod rewrite

# Set working directory
WORKDIR /var/www/html

# Copy project files
COPY . .

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader

# Set correct document root
ENV APACHE_DOCUMENT_ROOT /var/www/html/web

# Update Apache config to serve from /web
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Ensure storage and cpresources directories exist
RUN mkdir -p /var/www/html/storage /var/www/html/web/cpresources

# Set correct permissions
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/web/cpresources



# Expose port 80
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
